# when then file is edited, stop jekyll serve in the terminal and then restart it

incremental: true
# livereload: true
defaults:
  - scope:
      path: ""
      type: "page"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"